<?php

/**
 * Seeds CRM deals for both tenants, including:
 *   - 6 Pixel Agency deals across all pipeline stages
 *   - 2 Nova Studio deals (minimal isolation proof)
 *   - Ghost roles, hard assignments, estimation resources, and deal overheads
 *     for the Pixel Agency deals so the Estimation tab and AI Team Builder
 *     have realistic data to work with.
 */

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CrmDealSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            $now = Carbon::now()->toDateTimeString();

            // ── Pixel Agency Deals ──────────────────────────────────────
            DB::table('deals')->insert([
                [
                    'id' => DemoDataMap::DEAL_HARTWELL_ID,
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'name' => 'Brand Refresh',
                    'client' => 'Hartwell Retail Co',
                    'contact_name' => 'Emma Hartwell',
                    'contact_email' => 'emma@hartwellretail.com',
                    'contact_phone' => '+1-555-0101',
                    'estimated_value' => 45000.00,
                    'win_probability' => 20,
                    'status' => 'lead',
                    'expected_close_date' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                    'lead_source' => 'inbound',
                    'client_budget' => 42000.00,
                    'timeline_months' => 2,
                    'workload_hours' => 320.00,
                    'workload_description' => 'Complete brand identity overhaul including logo, colour palette, typography, and style guide for retail chain.',
                    'wizard_step' => 'context',
                    'target_margin' => 30.00,
                    'base_labor_cost' => 24000.00,
                    'overhead_cost' => 4800.00,
                    'buffer_cost' => 2400.00,
                    'total_estimated_cost' => 31200.00,
                    'estimated_gross_profit' => 10800.00,
                    'won_at' => null,
                    'lost_at' => null,
                    'win_reason' => null,
                    'loss_reason' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => DemoDataMap::DEAL_SUNRISE_ID,
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'name' => 'Mobile App MVP',
                    'client' => 'Sunrise Fintech',
                    'contact_name' => 'David Park',
                    'contact_email' => 'david@sunrisefintech.com',
                    'contact_phone' => '+1-555-0102',
                    'estimated_value' => 95000.00,
                    'win_probability' => 40,
                    'status' => 'inquiry',
                    'expected_close_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
                    'lead_source' => 'referral',
                    'client_budget' => 90000.00,
                    'timeline_months' => 4,
                    'workload_hours' => 720.00,
                    'workload_description' => 'Cross-platform mobile MVP for peer-to-peer lending. React Native + Node.js backend. OAuth 2.0, Plaid integration.',
                    'wizard_step' => 'estimation',
                    'target_margin' => 32.00,
                    'base_labor_cost' => 52000.00,
                    'overhead_cost' => 10400.00,
                    'buffer_cost' => 5200.00,
                    'total_estimated_cost' => 67600.00,
                    'estimated_gross_profit' => 22400.00,
                    'won_at' => null,
                    'lost_at' => null,
                    'win_reason' => null,
                    'loss_reason' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'name' => 'Dashboard Redesign',
                    'client' => 'BluePeak Logistics',
                    'contact_name' => 'Lisa Carter',
                    'contact_email' => 'lisa@bluepeaklogistics.com',
                    'contact_phone' => '+1-555-0103',
                    'estimated_value' => 65000.00,
                    'win_probability' => 75,
                    'status' => 'proposal',
                    'expected_close_date' => Carbon::now()->addMonth()->format('Y-m-d'),
                    'lead_source' => 'partner',
                    'client_budget' => 62000.00,
                    'timeline_months' => 3,
                    'workload_hours' => 480.00,
                    'workload_description' => 'Redesign legacy logistics dashboard with real-time map tracking, route optimisation views, and driver-scheduling widgets. Tech: Next.js, Mapbox, D3.',
                    'wizard_step' => 'staffing',
                    'target_margin' => 30.00,
                    'base_labor_cost' => 36000.00,
                    'overhead_cost' => 7200.00,
                    'buffer_cost' => 3600.00,
                    'total_estimated_cost' => 46800.00,
                    'estimated_gross_profit' => 15200.00,
                    'won_at' => null,
                    'lost_at' => null,
                    'win_reason' => null,
                    'loss_reason' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => DemoDataMap::DEAL_MERIDIAN_ID,
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'name' => 'Patient Portal',
                    'client' => 'Meridian Health',
                    'contact_name' => 'Dr. James Nguyen',
                    'contact_email' => 'j.nguyen@meridianhealth.org',
                    'contact_phone' => '+1-555-0104',
                    'estimated_value' => 120000.00,
                    'win_probability' => 90,
                    'status' => 'contract',
                    'expected_close_date' => Carbon::now()->addWeeks(2)->format('Y-m-d'),
                    'lead_source' => 'cold_outreach',
                    'client_budget' => 115000.00,
                    'timeline_months' => 5,
                    'workload_hours' => 960.00,
                    'workload_description' => 'HIPAA-compliant patient portal with appointment booking, telehealth video calls, and EHR sync. React frontend, Laravel API.',
                    'wizard_step' => 'complete',
                    'target_margin' => 28.00,
                    'base_labor_cost' => 64000.00,
                    'overhead_cost' => 12800.00,
                    'buffer_cost' => 6400.00,
                    'total_estimated_cost' => 83200.00,
                    'estimated_gross_profit' => 31800.00,
                    'won_at' => null,
                    'lost_at' => null,
                    'win_reason' => null,
                    'loss_reason' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => DemoDataMap::DEAL_APEX_ID,
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'name' => 'IoT Platform',
                    'client' => 'Apex Manufacturing',
                    'contact_name' => 'Robert Steele',
                    'contact_email' => 'rsteele@apex-mfg.com',
                    'contact_phone' => '+1-555-0105',
                    'estimated_value' => 180000.00,
                    'win_probability' => 100,
                    'status' => 'won',
                    'expected_close_date' => Carbon::now()->subMonths(2)->format('Y-m-d'),
                    'lead_source' => 'event',
                    'client_budget' => 175000.00,
                    'timeline_months' => 6,
                    'workload_hours' => 1440.00,
                    'workload_description' => 'Industrial IoT monitoring platform with real-time sensor ingestion, anomaly detection dashboards, and predictive maintenance alerts. Node.js, TimescaleDB, Grafana.',
                    'wizard_step' => 'complete',
                    'target_margin' => 35.00,
                    'base_labor_cost' => 84000.00,
                    'overhead_cost' => 16800.00,
                    'buffer_cost' => 8400.00,
                    'total_estimated_cost' => 109200.00,
                    'estimated_gross_profit' => 65800.00,
                    'won_at' => Carbon::now()->subMonths(2)->toDateTimeString(),
                    'lost_at' => null,
                    'win_reason' => 'Strong technical proposal and existing manufacturing vertical references.',
                    'loss_reason' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => DemoDataMap::DEAL_SUMMIT_ID,
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'name' => 'LMS Upgrade',
                    'client' => 'Summit Education',
                    'contact_name' => 'Karen Walsh',
                    'contact_email' => 'kwalsh@summitedu.org',
                    'contact_phone' => '+1-555-0106',
                    'estimated_value' => 55000.00,
                    'win_probability' => 0,
                    'status' => 'lost',
                    'expected_close_date' => Carbon::now()->subMonth()->format('Y-m-d'),
                    'lead_source' => 'social',
                    'client_budget' => 35000.00,
                    'timeline_months' => 3,
                    'workload_hours' => 400.00,
                    'workload_description' => 'Upgrade legacy Moodle instance with custom gamification plugins, mobile PWA wrapper, and SSO integration.',
                    'wizard_step' => 'context',
                    'target_margin' => 25.00,
                    'base_labor_cost' => 22000.00,
                    'overhead_cost' => 4400.00,
                    'buffer_cost' => 2200.00,
                    'total_estimated_cost' => 28600.00,
                    'estimated_gross_profit' => 6400.00,
                    'won_at' => null,
                    'lost_at' => Carbon::now()->subMonth()->toDateTimeString(),
                    'win_reason' => null,
                    'loss_reason' => 'Budget constraints; client chose offshore vendor at 40 % lower rate.',
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);

            // ── Nova Studio Deals ─────────────────────────────────────────
            DB::table('deals')->insert([
                [
                    'id' => DemoDataMap::NOVA_DEAL1_ID,
                    'tenant_id' => DemoDataMap::NOVA_TENANT_ID,
                    'name' => 'Portfolio Site',
                    'client' => 'Artisan Coffee Roasters',
                    'contact_name' => 'Marco Bellini',
                    'contact_email' => 'marco@artisancoffee.com',
                    'contact_phone' => '+1-555-0201',
                    'estimated_value' => 12000.00,
                    'win_probability' => 60,
                    'status' => 'proposal',
                    'expected_close_date' => Carbon::now()->addWeeks(3)->format('Y-m-d'),
                    'lead_source' => 'referral',
                    'client_budget' => 11000.00,
                    'timeline_months' => 1,
                    'workload_hours' => 120.00,
                    'workload_description' => 'Single-page portfolio with WebGL product visualiser and Shopify Buy Button integration.',
                    'wizard_step' => 'estimation',
                    'target_margin' => 30.00,
                    'base_labor_cost' => 6400.00,
                    'overhead_cost' => 1280.00,
                    'buffer_cost' => 640.00,
                    'total_estimated_cost' => 8320.00,
                    'estimated_gross_profit' => 2680.00,
                    'won_at' => null,
                    'lost_at' => null,
                    'win_reason' => null,
                    'loss_reason' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => DemoDataMap::NOVA_DEAL2_ID,
                    'tenant_id' => DemoDataMap::NOVA_TENANT_ID,
                    'name' => 'Marketing Campaign',
                    'client' => 'Urban Fitness',
                    'contact_name' => 'Nina Torres',
                    'contact_email' => 'nina@urbanfitness.com',
                    'contact_phone' => '+1-555-0202',
                    'estimated_value' => 8000.00,
                    'win_probability' => 30,
                    'status' => 'lead',
                    'expected_close_date' => Carbon::now()->addMonths(1)->format('Y-m-d'),
                    'lead_source' => 'social',
                    'client_budget' => 7500.00,
                    'timeline_months' => 1,
                    'workload_hours' => 80.00,
                    'workload_description' => 'Social media asset pack, landing page, and animated ad banners for Q3 gym membership push.',
                    'wizard_step' => 'context',
                    'target_margin' => 25.00,
                    'base_labor_cost' => 4800.00,
                    'overhead_cost' => 960.00,
                    'buffer_cost' => 480.00,
                    'total_estimated_cost' => 6240.00,
                    'estimated_gross_profit' => 1260.00,
                    'won_at' => null,
                    'lost_at' => null,
                    'win_reason' => null,
                    'loss_reason' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);

            // ── Ghost Roles (Pixel Agency) ──────────────────────────────
            $ghostRoleRows = [
                // Hartwell — Lead (design-heavy)
                ['deal_id' => DemoDataMap::DEAL_HARTWELL_ID, 'role_type' => 'design', 'quantity' => 2, 'months' => 2, 'salary' => 6000, 'min' => 5000, 'max' => 7000],
                ['deal_id' => DemoDataMap::DEAL_HARTWELL_ID, 'role_type' => 'pm',     'quantity' => 1, 'months' => 2, 'salary' => 6800, 'min' => 6000, 'max' => 7500],

                // Sunrise — Inquiry (full stack)
                ['deal_id' => DemoDataMap::DEAL_SUNRISE_ID, 'role_type' => 'backend',  'quantity' => 2, 'months' => 4, 'salary' => 7200, 'min' => 6000, 'max' => 8000],
                ['deal_id' => DemoDataMap::DEAL_SUNRISE_ID, 'role_type' => 'frontend', 'quantity' => 2, 'months' => 4, 'salary' => 6800, 'min' => 5500, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_SUNRISE_ID, 'role_type' => 'pm',       'quantity' => 1, 'months' => 4, 'salary' => 6800, 'min' => 6000, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_SUNRISE_ID, 'role_type' => 'qa',       'quantity' => 1, 'months' => 3, 'salary' => 5200, 'min' => 4500, 'max' => 6000],

                // BluePeak — Proposal (AI demo deal)
                ['deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID, 'role_type' => 'frontend', 'quantity' => 2, 'months' => 3, 'salary' => 6800, 'min' => 5500, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID, 'role_type' => 'backend',  'quantity' => 1, 'months' => 3, 'salary' => 7200, 'min' => 6000, 'max' => 8000],
                ['deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID, 'role_type' => 'design',   'quantity' => 1, 'months' => 2, 'salary' => 6000, 'min' => 5000, 'max' => 7000],
                ['deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID, 'role_type' => 'pm',       'quantity' => 1, 'months' => 3, 'salary' => 6800, 'min' => 6000, 'max' => 7500],

                // Meridian — Contract
                ['deal_id' => DemoDataMap::DEAL_MERIDIAN_ID, 'role_type' => 'backend',  'quantity' => 2, 'months' => 5, 'salary' => 7200, 'min' => 6000, 'max' => 8000],
                ['deal_id' => DemoDataMap::DEAL_MERIDIAN_ID, 'role_type' => 'frontend', 'quantity' => 2, 'months' => 5, 'salary' => 6800, 'min' => 5500, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_MERIDIAN_ID, 'role_type' => 'pm',       'quantity' => 1, 'months' => 5, 'salary' => 6800, 'min' => 6000, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_MERIDIAN_ID, 'role_type' => 'qa',       'quantity' => 1, 'months' => 4, 'salary' => 5200, 'min' => 4500, 'max' => 6000],

                // Apex — Won (active project)
                ['deal_id' => DemoDataMap::DEAL_APEX_ID, 'role_type' => 'backend',  'quantity' => 3, 'months' => 6, 'salary' => 7200, 'min' => 6000, 'max' => 8000],
                ['deal_id' => DemoDataMap::DEAL_APEX_ID, 'role_type' => 'frontend', 'quantity' => 2, 'months' => 6, 'salary' => 6800, 'min' => 5500, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_APEX_ID, 'role_type' => 'pm',       'quantity' => 1, 'months' => 6, 'salary' => 6800, 'min' => 6000, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_APEX_ID, 'role_type' => 'qa',       'quantity' => 1, 'months' => 5, 'salary' => 5200, 'min' => 4500, 'max' => 6000],
                ['deal_id' => DemoDataMap::DEAL_APEX_ID, 'role_type' => 'design',   'quantity' => 1, 'months' => 3, 'salary' => 6000, 'min' => 5000, 'max' => 7000],

                // Summit — Lost
                ['deal_id' => DemoDataMap::DEAL_SUMMIT_ID, 'role_type' => 'backend',  'quantity' => 1, 'months' => 3, 'salary' => 7200, 'min' => 6000, 'max' => 8000],
                ['deal_id' => DemoDataMap::DEAL_SUMMIT_ID, 'role_type' => 'frontend', 'quantity' => 1, 'months' => 3, 'salary' => 6800, 'min' => 5500, 'max' => 7500],
                ['deal_id' => DemoDataMap::DEAL_SUMMIT_ID, 'role_type' => 'design',   'quantity' => 1, 'months' => 2, 'salary' => 6000, 'min' => 5000, 'max' => 7000],
            ];

            foreach ($ghostRoleRows as $gr) {
                DB::table('deal_ghost_roles')->insert([
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => $gr['deal_id'],
                    'role_type' => $gr['role_type'],
                    'quantity' => $gr['quantity'],
                    'months' => $gr['months'],
                    'avg_monthly_salary' => $gr['salary'],
                    'min_monthly_salary' => $gr['min'],
                    'max_monthly_salary' => $gr['max'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }

            // ── Hard Assignments (won deal only: Apex) ──────────────────
            DB::table('deal_hard_assignments')->insert([
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_APEX_ID,
                    'employee_id' => DemoDataMap::PIXEL_EMP_DEV_ID,
                    'allocated_hours' => 640.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_APEX_ID,
                    'employee_id' => DemoDataMap::PIXEL_EMP_DESIGN_ID,
                    'allocated_hours' => 320.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_APEX_ID,
                    'employee_id' => DemoDataMap::PIXEL_EMP_PM_ID,
                    'allocated_hours' => 480.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_APEX_ID,
                    'employee_id' => DemoDataMap::PIXEL_EMP_QA_ID,
                    'allocated_hours' => 240.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);

            // ── Estimation Resources (BluePeak proposal deal) ───────────
            DB::table('estimation_resources')->insert([
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'job_role_id' => DemoDataMap::PIXEL_ROLE_DEV_ID,
                    'role_id' => (string) DemoDataMap::PIXEL_ROLE_DEV_ID,
                    'feature_name' => 'Real-time map tracking widget',
                    'hours' => 120.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'job_role_id' => DemoDataMap::PIXEL_ROLE_DEV_ID,
                    'role_id' => (string) DemoDataMap::PIXEL_ROLE_DEV_ID,
                    'feature_name' => 'Route optimisation engine',
                    'hours' => 160.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'job_role_id' => DemoDataMap::PIXEL_ROLE_DESIGN_ID,
                    'role_id' => (string) DemoDataMap::PIXEL_ROLE_DESIGN_ID,
                    'feature_name' => 'Dashboard UI / UX overhaul',
                    'hours' => 100.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'job_role_id' => DemoDataMap::PIXEL_ROLE_PM_ID,
                    'role_id' => (string) DemoDataMap::PIXEL_ROLE_PM_ID,
                    'feature_name' => 'Sprint planning & stakeholder sync',
                    'hours' => 80.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'job_role_id' => DemoDataMap::PIXEL_ROLE_QA_ID,
                    'role_id' => (string) DemoDataMap::PIXEL_ROLE_QA_ID,
                    'feature_name' => 'E2E testing & performance audit',
                    'hours' => 60.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);

            // ── Deal Overheads (BluePeak proposal deal) ─────────────────
            DB::table('deal_overheads')->insert([
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'name' => 'Mapbox API Licensing',
                    'cost' => 2400.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'id' => Str::uuid()->toString(),
                    'tenant_id' => DemoDataMap::PIXEL_TENANT_ID,
                    'deal_id' => DemoDataMap::DEAL_BLUEPEAK_ID,
                    'name' => 'Third-party security audit',
                    'cost' => 1800.00,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);
        });
    }
}
